services:

  broker:
    image: apache/kafka
    hostname: broker
    container_name: broker
    ports:
      - '9092:9092'
    user: '${CURRENT_UID}:${CURRENT_GID}'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

  clickhouse:
    image: clickhouse/clickhouse-server
    hostname: clickhouse
    container_name: clickhouse
    ports:
      - '8123:8123'
    user: '${CURRENT_UID}:${CURRENT_GID}'
    environment:
      CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS: 1
    volumes:
       - ./clickhouse/var/lib/clickhouse/:/var/lib/clickhouse/
       - ./clickhouse/var/log/clickhouse-server/:/var/log/clickhouse-server/
       - ./clickhouse/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
       - ./clickhouse/etc/clickhouse-server/config.d/:/etc/clickhouse-server/config.d/
       - ./clickhouse/etc/clickhouse-server/users.d/:/etc/clickhouse-server/users.d/

  grafana:
    image: grafana/grafana-enterprise
    hostname: grafana
    container_name: grafana
    ports:
      - '3000:3000'
    user: '${CURRENT_UID}:${CURRENT_GID}'
    environment:
     - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
     - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
    volumes:
      - './grafana/etc/grafana/:/etc/grafana/'

  data-generator:
    hostname: data-generator
    container_name: data-generator
    build:
      dockerfile: ./data-generator/Dockerfile
    volumes:
      - './data-generator:/app'
    command: python3 main.py

  flink-jobmanager:
    build:
      dockerfile: ./flink/Dockerfile
    hostname: flink-jobmanager
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    volumes:
      - './flink/jobs:/opt/flink/jobs'
      - './flink/usrlib:/opt/flink/usrlib'
      - './flink/entrypoint.sh:/opt/flink/entrypoint.sh'
    command: ["/opt/flink/entrypoint.sh"]
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager     

  flink-taskmanager:
    build:
      dockerfile: ./flink/Dockerfile
    hostname: flink-taskmanager
    container_name: flink-taskmanager
    depends_on:
      - flink-jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2     

