apiVersion: 1

datasources:
  - name: clickhouse
    type: grafana-clickhouse-datasource
    editable: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      username: default
      tlsSkipVerify: false